export const ROLES = {
  ADMIN: 'ADMIN',
  HR: 'HR'
};

export const CANDIDATE_STATUS = {
  PENDING: 'PENDING',
  WHATSAPP_SENT: 'WHATSAPP_SENT',
  WHATSAPP_REPLIED: 'WHATSAPP_REPLIED',
  VOICE_FALLBACK_DISPATCHED: 'VOICE_FALLBACK_DISPATCHED',
  INTEREST_DECLINED: 'INTEREST_DECLINED',
  SCREENED: 'SCREENED',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED'
};

export const WHATSAPP_STATUS = {
  NOT_SENT: 'NOT_SENT',
  SENT: 'SENT',
  REPLIED: 'REPLIED',
  EXPIRED: 'EXPIRED'
};

export const CONSENT_STATUS = {
  PENDING: 'PENDING',
  OPTED_IN: 'OPTED_IN',
  OPTED_OUT: 'OPTED_OUT'
};

export const WHATSAPP_TIMEOUT_MINUTES = parseInt(process.env.WHATSAPP_TIMEOUT_MINUTES || '15', 10);

// Priority 5 — Calling Hours Guardrail
export const CALLING_HOURS_START = parseInt(process.env.CALLING_HOURS_START || '9', 10);
export const CALLING_HOURS_END = parseInt(process.env.CALLING_HOURS_END || '19', 10);
export const CALLING_TIMEZONE = process.env.CALLING_TIMEZONE || 'Asia/Kolkata';
