export const ROLES = {
  ADMIN: 'ADMIN',
  HR: 'HR'
};

export const CANDIDATE_STATUS = {
  PENDING: 'PENDING',
  WHATSAPP_SENT: 'WHATSAPP_SENT',
  WHATSAPP_REPLIED: 'WHATSAPP_REPLIED',
  MAGIC_LINK_SENT: 'MAGIC_LINK_SENT',
  INTERVIEW_IN_PROGRESS: 'INTERVIEW_IN_PROGRESS',
  VOICE_FALLBACK_DISPATCHED: 'VOICE_FALLBACK_DISPATCHED',
  INTEREST_DECLINED: 'INTEREST_DECLINED',
  SCREENED: 'SCREENED',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
  DATA_ERASED_DPDP: 'DATA_ERASED_DPDP'
};

export const WHATSAPP_STATUS = {
  NOT_SENT: 'NOT_SENT',
  SENT: 'SENT',
  REPLIED: 'REPLIED',
  EXPIRED: 'EXPIRED'
};

export const CONSENT_STATUS = {
  PENDING: 'PENDING',
  OPTED_IN: 'OPTED_IN',
  OPTED_OUT: 'OPTED_OUT'
};

export const DPDP_ACTIONS = {
  CONSENT_GRANTED: 'CONSENT_GRANTED',
  CONSENT_DECLINED: 'CONSENT_DECLINED',
  RIGHT_TO_ERASURE_PURGED: 'RIGHT_TO_ERASURE_PURGED',
  DATA_ACCESSED: 'DATA_ACCESSED'
};

export const DPDP_CHANNELS = {
  WHATSAPP: 'WHATSAPP',
  WEB_SCREENING: 'WEB_SCREENING',
  HR_PORTAL: 'HR_PORTAL'
};

export const MAGIC_LINK_EXPIRY_HOURS = parseInt(process.env.MAGIC_LINK_EXPIRY_HOURS || '48', 10);
export const WHATSAPP_TIMEOUT_MINUTES = parseInt(process.env.WHATSAPP_TIMEOUT_MINUTES || '1440', 10); // 24 hours default in omnichannel

// Priority 5 — Calling Hours Guardrail
export const CALLING_HOURS_START = parseInt(process.env.CALLING_HOURS_START || '9', 10);
export const CALLING_HOURS_END = parseInt(process.env.CALLING_HOURS_END || '19', 10);
export const CALLING_TIMEZONE = process.env.CALLING_TIMEZONE || 'Asia/Kolkata';
export const MAX_CALL_ATTEMPTS = parseInt(process.env.MAX_CALL_ATTEMPTS || '2', 10);

